# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/laptop59/Documents/score-on-the-go

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/laptop59/Documents/score-on-the-go

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laptop59/Documents/score-on-the-go/CMakeFiles /home/laptop59/Documents/score-on-the-go//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laptop59/Documents/score-on-the-go/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named score-on-the-go

# Build rule for target.
score-on-the-go: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 score-on-the-go
.PHONY : score-on-the-go

# fast build rule for target.
score-on-the-go/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/build
.PHONY : score-on-the-go/fast

src/ball.o: src/ball.cpp.o
.PHONY : src/ball.o

# target to build an object file
src/ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/ball.cpp.o
.PHONY : src/ball.cpp.o

src/ball.i: src/ball.cpp.i
.PHONY : src/ball.i

# target to preprocess a source file
src/ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/ball.cpp.i
.PHONY : src/ball.cpp.i

src/ball.s: src/ball.cpp.s
.PHONY : src/ball.s

# target to generate assembly for a file
src/ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/ball.cpp.s
.PHONY : src/ball.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/serializer.o: src/serializer.cpp.o
.PHONY : src/serializer.o

# target to build an object file
src/serializer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/serializer.cpp.o
.PHONY : src/serializer.cpp.o

src/serializer.i: src/serializer.cpp.i
.PHONY : src/serializer.i

# target to preprocess a source file
src/serializer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/serializer.cpp.i
.PHONY : src/serializer.cpp.i

src/serializer.s: src/serializer.cpp.s
.PHONY : src/serializer.s

# target to generate assembly for a file
src/serializer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/serializer.cpp.s
.PHONY : src/serializer.cpp.s

src/texture_library.o: src/texture_library.cpp.o
.PHONY : src/texture_library.o

# target to build an object file
src/texture_library.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/texture_library.cpp.o
.PHONY : src/texture_library.cpp.o

src/texture_library.i: src/texture_library.cpp.i
.PHONY : src/texture_library.i

# target to preprocess a source file
src/texture_library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/texture_library.cpp.i
.PHONY : src/texture_library.cpp.i

src/texture_library.s: src/texture_library.cpp.s
.PHONY : src/texture_library.s

# target to generate assembly for a file
src/texture_library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/score-on-the-go.dir/build.make CMakeFiles/score-on-the-go.dir/src/texture_library.cpp.s
.PHONY : src/texture_library.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... score-on-the-go"
	@echo "... src/ball.o"
	@echo "... src/ball.i"
	@echo "... src/ball.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/serializer.o"
	@echo "... src/serializer.i"
	@echo "... src/serializer.s"
	@echo "... src/texture_library.o"
	@echo "... src/texture_library.i"
	@echo "... src/texture_library.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

